=== aimparency/v7/protocol/schemas/phase.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/aimparency/v7/blob/main/protocol/schemas/phase.schema.json",
  "title": "Aimparency phase",
  "description": ".bowman/phases/<id>.json: one phase and the ideas committed to it. Data model version 5.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "from": {
      "type": "number"
    },
    "to": {
      "type": "number"
    },
    "order": {
      "type": "integer",
      "minimum": 0
    },
    "parent": {
      "anyOf": [
        {
          "type": "string",
          "format": "uuid"
        },
        {
          "type": "null"
        }
      ]
    },
    "childPhaseIds": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid"
      }
    },
    "commitments": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid"
      }
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "parent",
    "commitments",
    "name"
  ],
  "additionalProperties": false
}

=== aimparency/v7/.bowman/phases/f51f8930-c937-4c66-9db8-d4d313e6d286.json
{
  "id": "f51f8930-c937-4c66-9db8-d4d313e6d286",
  "from": 1764284400000,
  "to": 1766530800000,
  "parent": null,
  "childPhaseIds": [
    "ab939925-1be6-43fc-b7a9-958b49b2c66a",
    "4c960ff4-05ba-4ff8-b523-1a104d750503",
    "61ebf544-cd45-48d1-9c11-9763e8674ce1"
  ],
  "commitments": [
    "865e4b34-0c68-4e34-9361-809c4d90db4c",
    "d59d03c1-45dd-48db-98c2-49b61b481f07",
    "1c60ee55-0627-43d6-8393-e912fc2e52a2",
    "abc3d503-5945-45eb-8122-be5e33b2ccea",
    "c858c337-506e-494b-bfe3-c32e4db02aaf",
    "0f577668-ca34-4e7a-a7a8-9f97bc91454e",
    "97d2e473-64b4-4de8-99c8-d8a7a064ee43",
    "33be4e0c-fa52-42ba-a86b-4c209b34e2be",
    "a776e5cc-0302-48f0-8e90-e85354851feb",
    "f2337265-ffc6-4ae8-a421-d6e4d5540210",
    "36794f88-d947-45bb-a6b6-5f8da034ed0f",
    "1d0dcba3-11da-44c9-a66d-ed80ac100ea5",
    "5619ff4e-999d-4908-a2d6-09cb730bfa41",
    "ca93615f-6364-4b90-aa3a-1e78c9939e55",
    "b4903845-c07b-482a-a6c6-a5c9fdf3de71",
    "802342cf-de8f-4614-8915-74e7a0800980",
    "dec42d50-03ca-4dce-9e1f-31f6c20a7b52",
    "f0c0ffe0-4460-4346-97e4-4cd423b3fefa",
    "f545d42a-0b43-4587-97f2-67eede424f99",
    "77383b31-f45d-4994-be03-d3aed0f16f1c",
    "dc0f6634-8873-4f1b-8bd1-5ac72dbf8759",
    "0b63290f-d42e-44c5-b0ba-e92a37fc67cb",
    "49258e32-69a4-4b61-9cc4-a54bac439d32",
    "c71bb0e6-9822-49a3-83dd-d6e6d0649433",
    "3ed98052-9d15-466e-b3a5-3082ba3e50b3",
    "65f63194-8cf2-4355-b687-f1df2759e5ee",
    "bed74658-63e8-4a7b-b7ab-b69655b39cd8",
    "0e931650-0fdb-4a3a-9f44-6dd05cf1ceac",
    "b3c1bd1a-a503-45af-8c3a-3d3bee567f47"
  ],
  "name": "next-level"
}

=== aimparency/v7/.bowman/phases/ab939925-1be6-43fc-b7a9-958b49b2c66a.json
{
  "id": "ab939925-1be6-43fc-b7a9-958b49b2c66a",
  "from": 1765238400000,
  "to": 1765843200000,
  "order": 5,
  "parent": "f51f8930-c937-4c66-9db8-d4d313e6d286",
  "childPhaseIds": [],
  "commitments": [
    "50188560-6c74-4005-8061-7e1090f28895",
    "726a6360-6e93-4a0f-95b6-1863af2600e5",
    "81812958-054f-4da1-b6fa-62c930b7014d",
    "8419f493-e9ee-4917-b858-32bdbb0b2dca",
    "93af91df-704e-4d84-9b9b-f9feed6898b9",
    "997f5b3c-ad9b-4187-a4a2-34bb86daf1b7",
    "cb96039f-3f52-42ac-be2f-4023679f44a2",
    "dc90ccef-5e1e-4a57-ae57-9833bde682fd",
    "dfee4708-69b8-4850-8228-e59cdc4e5860",
    "eaabc313-ff9c-418b-9d7e-3fc84dd06af1",
    "2a32fb69-21e3-49d9-abe2-68e1ba1365dc"
  ],
  "name": "Social Automation Sprint"
}

=== aimparency/v7/.bowman/phases/8497d7b8-7729-4dde-b868-3cdcd2a749d6.json
{
  "id": "8497d7b8-7729-4dde-b868-3cdcd2a749d6",
  "from": 1787522400000,
  "to": 1788213599000,
  "parent": "bb7ce28d-0eee-4243-a489-fd4eab223c35",
  "childPhaseIds": [],
  "commitments": [
    "86d965a6-3f9b-41ba-97c1-86c51323bcd7"
  ],
  "name": "August · trip-content readiness · by 31 Aug 2026"
}

=== aimparency/v7/.bowman/phases/618b92d0-70cc-434c-b2b5-ee9fcfefc25a.json
{
  "id": "618b92d0-70cc-434c-b2b5-ee9fcfefc25a",
  "from": 1767225600000,
  "to": 1774915200000,
  "parent": "9a4b8d5f-b63a-4704-a74d-4bc82f9c03b5",
  "childPhaseIds": [
    "5c2f9450-0feb-4755-b59a-081e9ab43037",
    "2abfd425-ee90-4286-a019-ba0ff703c73a",
    "9e2e29ae-54b9-4844-b833-0344d6d18951",
    "33ccb9f5-38de-463b-b7be-7c5615817564"
  ],
  "commitments": [
    "0cefe646-447b-412a-b4f6-53167668b0ee",
    "0d6d4f9c-cc6c-4072-9765-996aac58cd22",
    "0f8868ba-7ac5-46f7-a23a-7ca3e0cb43d4",
    "035f3963-180a-49c2-8d42-8889ed5dbc50",
    "ad4776b8-7dfe-47f5-8bc6-54a4f9d39d68",
    "5dd6a07a-5e23-4eec-a674-6c28e8096e6c",
    "0855f086-1055-4214-81d5-a422e1189707",
    "b3fa8f91-37d5-45d6-86c0-bf6c5afcb8dc",
    "88d7bcb6-c79e-43c3-963f-cfd7d8deb354",
    "8ae9e8da-69aa-4321-8d66-2533716daf58",
    "54afad1d-4660-4908-8043-eeea348eaf90",
    "9c44aab0-68cd-42ba-a192-272459bea4f1",
    "17f8e9b2-ba9c-420c-a099-c0912db7275b",
    "c58ae2b8-9d4b-444e-8c07-5d25e6b6fc1b",
    "8e63ff9c-f48f-40fe-b7f5-bb94fd0af200",
    "6bfa572e-b451-44e0-b36d-fe4e3ab6f582",
    "cf695de6-3a8e-4830-a274-14a942998c04",
    "ff2e9a3b-b65e-4e45-abec-c19cffe59bad",
    "9f83a877-1b9d-42a4-a7f8-72344ff27459",
    "d7f7b02f-e650-4cb5-aeaa-e7ef36279b67",
    "980ccb42-ff50-4384-8bab-cfe9646e83f0",
    "e0289c2f-8fe7-4875-a46a-21709c8d8295",
    "e2846e8e-29e8-4584-b250-9e0dcfd3c787",
    "bc9b94d3-606f-4756-a22a-52444f6021ef",
    "f1550eb7-d02e-40bc-af94-1fb1076076bd",
    "bc0a18cf-63c5-413f-9faf-5a312241deff",
    "96adb3d0-5827-432e-8a48-8d26754fcaed",
    "73e72297-47c8-4a88-b7eb-5d6e7e575001",
    "0eba57d1-6f4f-49a1-bf75-a793792d7d6f",
    "69321b93-d540-45a9-9a25-8f2d5254d43c",
    "365e78d0-ed64-47d7-9902-b575d493c6e4",
    "c4ab85c2-0497-48de-ae93-3dc7b4c2aa60",
    "3427a68e-791e-4f59-bc46-bd72d85e6d71",
    "756cf129-0c66-43dd-84cf-58e94450e325",
    "22c4140b-9ae2-4805-9071-a3f30b1c4ec3",
    "3ea51517-fc9c-4215-ac5b-79ec2a21f6b2",
    "fa09c443-dd67-48c9-9655-122b18c4defd",
    "fc51df6c-c059-4181-9645-a1ed11cd6beb",
    "992b990a-d90f-4cf9-8ec6-e1ff4678b1bf",
    "541a9365-8d41-4835-aab7-823f5807b6fb",
    "e2dc1422-5f19-4841-9f17-d38296886461",
    "6da6ecb2-04e7-426e-95d1-66566d11182b",
    "3c0b4344-07bd-48b5-a800-6cf02332ea45",
    "324c369b-1227-433f-b853-7ad79dec920b",
    "5558caa1-cb54-40a9-a383-8b4c77568226",
    "b2d985ab-398d-4c68-b781-9ceaac505f81",
    "439230f6-4347-4abc-a23b-2f67e58739bd",
    "facbacb5-1589-4b73-8ecb-97d7bb32bd99",
    "9594aa9b-e7f0-4879-9d9b-52ae20f8a52d",
    "74b079de-667c-47f6-8017-fb202e2affd9",
    "038522a0-3f35-4f06-82ef-2dd0b2d3736e",
    "0fee8918-1087-4e7f-bb0e-ba506be3a8c6",
    "67c40d89-123f-4c3b-a8aa-0b703d274b14",
    "dadcd0a7-511b-4152-b971-2c11ea17bc40",
    "2ff1fd7a-7e02-4197-a558-174622db7cbe",
    "300f5452-f7e9-452d-9f3e-078c988e8af8",
    "b69e9372-2207-4624-8a18-9a814f3938b2",
    "fa735173-548c-4830-84a4-de7738024cf7",
    "f2337265-ffc6-4ae8-a421-d6e4d5540210"
  ],
  "name": "Q1 2026: Scale Experience Mining"
}
